import './globals.css'
import { Inter } from 'next/font/google'
import AuthProvider from '@/copmponents/AuthProvider'
import { ToastContainer } from 'react-toastify'
import Navbar from '@/copmponents/Navbar'
import { Toaster } from 'react-hot-toast'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
 <Toaster/>
        <Navbar/>
        {children}
        </AuthProvider>
        </body>
    </html>
  )
}
